### ISSUE TITLE
bad formatted 'poster' property on 'Search' endpoint

### ISSUE THREAD

**Issue by Shompi** [ChrisMichaelPerezSantiago/animeflv#1]
In the 'poster' property received by the api, the URL to the image is wrong formatted.

**Expected behavior**
Direct url to the poster image.
 
```javascript
{
"poster": "https://animeflv.nethttps://animeflv.net/uploads/animes/covers/3170.jpg"
}
```
you can see that "https://animeflv.net" is written twice.

**Comment by ChrisMichaelPerezSantiago** [comment]
_Hello @Shompi,_

_Thanks for letting me know._
_The value of the poster property was fixed #1
