### ISSUE TITLE
Añade la ID de los animes

### ISSUE THREAD

**Issue by paperrain** [ChrisMichaelPerezSantiago/animeflv#5]
Buenas, 
estaría bien si para "latestEpisodesAdded()" y "latestAnimeAdded()" añadieras los IDs de los animes, es decir tener el "enlace directo" a ese anime como haces con los capítulos en "latestAnimeAdded()".

Gracias,

**Comment by ChrisMichaelPerezSantiago** [comment]
_Hola @paperrain ,_

_Ya hice los debidos cambios que me has sugerido. 
Por ahora podrás ver los cambios usando las URLs de la API. Si estas usando la librería de npm tendrías que esperar a la próxima release ya que precisamente ayer hice el lanzamiento de la v1.0.4_

**Comment by paperrain** [comment]
Gracias @ChrisMichaelPerezSantiago 
Me acabo de percatar de que no sirve de mucho lo de la ID y creo que por eso lo tenias comentado (fallo mío). 

Podrías añadir que a través de esa ID llame a una función como haces con "getAnimeServers([id])" y muestre los capítulos(con sus ids) y la info del anime. ¿Seria posible, añadirlo?. 

Muchas gracias :)

**Comment by ChrisMichaelPerezSantiago** [comment]
_@paperrain ,_

_Creo no haberte entendido del todo._
_¿Puedes proveer un ejemplo de cómo visualizas tu propuesta en formato JSON?_

**Comment by paperrain** [comment]
@ChrisMichaelPerezSantiago 
Es básicamente lo que haces con el buscador, pero en vez de mostrar todos los animes encontrados, solo muestres el referido en la id, es decir algo como esto:

Llamas a la API y le pasas el valor a través de aquí por ejemplo: getAnimeInfo([id]) (ejemplo) y te devuelve esto:

`    {
      "title": "Tokyo Ghoul",
      "poster": "https://animeflv.nethttps://animeflv.net/uploads/animes/covers/1415.jpg",
      "synopsis": "Anime 4.5Extraños asesinatos se están sucediendo uno tras otro en Tokyo. Debido a las pruebas encontradas en las escenas, la policía concluye que los ataques son obra de ghouls que se comen a las personas. Kaneki y Hide, dos compañeros de clase, llegan a la conclusión de que si nadie ha visto nunca a esos necrófagos...",
      "debut": null,
      "type": "Anime",
      "rating": "4.5",
      "episodes": [
        {
          "nextEpisodeDate": null
        },
        {
          "episode": 12,
          "id": "28800/tokyo-ghoul-12",
          "imagePreview": "https://cdn.animeflv.net/screenshots/1415/12/th_3.jpg"
        },
        {
          "episode": 11,
          "id": "28459/tokyo-ghoul-11",
          "imagePreview": "https://cdn.animeflv.net/screenshots/1415/11/th_3.jpg"
        },
        {
          "episode": 10,
          "id": "28001/tokyo-ghoul-10",
          "imagePreview": "https://cdn.animeflv.net/screenshots/1415/10/th_3.jpg"
        },
        {
          "episode": 9,
          "id": "27741/tokyo-ghoul-9",
          "imagePreview": "https://cdn.animeflv.net/screenshots/1415/9/th_3.jpg"
        },
        {
          "episode": 8,
          "id": "27092/tokyo-ghoul-8",
          "imagePreview": "https://cdn.animeflv.net/screenshots/1415/8/th_3.jpg"
        },
        {
          "episode": 7,
          "id": "26689/tokyo-ghoul-7",
          "imagePreview": "https://cdn.animeflv.net/screenshots/1415/7/th_3.jpg"
        },
        {
          "episode": 6,
          "id": "26529/tokyo-ghoul-6",
          "imagePreview": "https://cdn.animeflv.net/screenshots/1415/6/th_3.jpg"
        },
        {
          "episode": 5,
          "id": "26431/tokyo-ghoul-5",
          "imagePreview": "https://cdn.animeflv.net/screenshots/1415/5/th_3.jpg"
        },
        {
          "episode": 4,
          "id": "26373/tokyo-ghoul-4",
          "imagePreview": "https://cdn.animeflv.net/screenshots/1415/4/th_3.jpg"
        },
        {
          "episode": 3,
          "id": "26278/tokyo-ghoul-3",
          "imagePreview": "https://cdn.animeflv.net/screenshots/1415/3/th_3.jpg"
        },
        {
          "episode": 2,
          "id": "26188/tokyo-ghoul-2",
          "imagePreview": "https://cdn.animeflv.net/screenshots/1415/2/th_3.jpg"
        },
        {
          "episode": 1,
          "id": "26103/tokyo-ghoul-1",
          "imagePreview": "https://cdn.animeflv.net/screenshots/1415/1/th_3.jpg"
        }
      ]
    }`

**Comment by ChrisMichaelPerezSantiago** [comment]
@paperrain  _Ya veo,_ 
_El problema es que ya hay personas usando la API en sus proyectos, y seria dañar la estructura actual._

**Comment by paperrain** [comment]
@ChrisMichaelPerezSantiago ¿Pero no seria un añadido, es decir no rompería la estructura? Como el video de promo de animes. ¿Pregunto solamente :P?

**Comment by ChrisMichaelPerezSantiago** [comment]
_@paperrain ,_

_Si, ya logré entenderte._

_Te recomiendo que habrás otro issue sobre ese tema._ 
_Así no mezclamos información adicional en este issue que es relacionado al id del anime._
